import { Product } from "./types/Product";
const productsList: Product[] = [
  {
    id: 1,
    orderId: "price_1MhsBuSHFlTkNXPtPwdVIA7t",
    companyName: "Behnam",
    name: "Norouzi S1 Shoes",
    price: 10,
    imgSrc: "/images/behnam_norouzi_F4rWoM3cYjI-min.png",
    discount: 10,
    rating: 4.13,
    couponId: "PIo70NCE",
  },
  {
    id: 2,
    orderId: "price_1MhsCpSHFlTkNXPtIEPZQfi4",
    companyName: "Hipkicks",
    name: "Hipkicks A2 Shoes",
    price: 20,
    discount: 20,
    imgSrc: "/images/hipkicks_HcqA34-uWo4-min.png",
    rating: 4.3,
    couponId: "L3zmvwEZ",
  },
  {
    id: 3,
    orderId: "price_1MhsDoSHFlTkNXPt69nucRKj",
    companyName: "Rachael",
    name: "Ren S2 Shoes",
    price: 30,
    imgSrc: "/images/rachael_ren_Ueu_6ZrVb80-min.png",
    discount: 25,
    rating: 4.2,
    couponId: "Xms5a2mx",
  },
  {
    id: 4,
    orderId: "price_1MhsEZSHFlTkNXPtEGtJ7Bvh",
    companyName: "Revolt",
    name: "Rev164 Shoes",
    price: 40,
    imgSrc: "/images/revolt_164_6wVEHfI-min.png",
    rating: 4.3,
    discount: 15,
    couponId: "lAhVYWm0",
  },
  {
    id: 5,
    orderId: "price_1MhsFJSHFlTkNXPtGuOENOD7",
    companyName: "Suddreth",
    name: "Will A1 Shoes",
    price: 50,
    imgSrc: "/images/will_suddreth_mgweTPIa2Pc-min.png",
    rating: 4.0,
    discount: 30,
    couponId: "kdeQPONv",
  },
];

export default productsList;
